[package]
name = "firestore-rules-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "*" 
serde_json = "1.0.108" 
serde = "*" 
lsp-types = "=0.95"
chumsky = "0.9.3"
regex = "1.10.3"
