name: Build

on:
  push:
    tags:
      - "*"

env:
  CARGO_INCREMENTAL: 0

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup update
      - run: cd lsp && cargo build --release
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: firestore-rules-lsp-${{ github.ref_name }}-win_x64
          path: lsp\target\release\firestore-rules-lsp.exe

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup update
      - run: cd lsp && cargo build --release
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: firestore-rules-lsp-${{ github.ref_name }}-linux_x64
          path: lsp/target/release/firestore-rules-lsp
          overwrite: true

  build_macos_intel:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v7
      - run: rustup update
      - run: cd lsp && cargo build --release
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: firestore-rules-lsp-${{ github.ref_name }}-mac_x64
          path: lsp/target/release/firestore-rules-lsp
          overwrite: true

  build_macos_arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - run: rustup update
      - run: cd lsp && cargo build --release
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: firestore-rules-lsp-${{ github.ref_name }}-mac_arm64
          path: lsp/target/release/firestore-rules-lsp
          overwrite: true
